### ISSUE TITLE
Accept a container name with space

### ISSUE THREAD

**Issue by jmeiss** [Qovery/qovery-cli#148]
**What would you like to be added**:
Accept a container name that has spaces and colons.

**Why is this needed**:
We have containers named:
- `DB migration`
- `rake mailer:daily_digest`

That we had to rename to remove the spaces and colons.

It's not a big issue bug that would be nicer to be able to deploy containers with the same characters that are allowed on the UI.

The command that doesn't work:
```
        qovery cronjob deploy \
          --organization <org> \
          --project WebApp \
          --environment staging \
          --cronjobs "rake mailer:admin_daily_digest,rake mailer:daily_digest" \
          --tag ${{ github.sha }} \
          --watch
```
Error message
```
Error: job 'rake mailer:admin_daily_digest' not found
```

Thanks in advance 🙏

**Comment by evoxmusic** [comment]
@jmeiss , thank you for reporting this issue. Can you check that the name of your service exists? I think `rake mailer:admin_daily_digest` does not exist. The CLI support spaces for service names if you surround them with double quotes (which is what you have done)

`qovery cronjob list`

**Comment by evoxmusic** [comment]
No worries :) Glad it works now
