### ISSUE TITLE
Be able to update an environment name

### ISSUE THREAD

**Issue by jmeiss** [Qovery/qovery-cli#149]
**What would you like to be added**:
`qovery environment rename` or anything similar that could allow us to rename an environment name.

**Why is this needed**:
When updating a PR name, we would like to synchronize it with the preview environment name

**Comment by evoxmusic** [comment]
Hi @jmeiss ,

Good news. The Qovery CLI v0.54 includes the command `qovery environment update` that you can use to change the name and type of your environment.

```bash
qovery environment update -e <your_env_name> --name <your_new_env_name|optional> --type <your_new_env_type|optional>
```

**Comment by jmeiss** [comment]
Hey @evoxmusic 

So fast!
Thank you very much for that new feature 🙏
