### ISSUE TITLE
Qovery run does not work on Windows 10

### ISSUE THREAD

**Issue by kkapelon** [Qovery/qovery-cli#15]
**What happened**:
qovery run says that I am not authenticated

**What you expected to happen**:
It should execute, since I just authenticated

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the quick start guide on Windows 10

**Anything else we need to know?**:
I am also attaching a screenshot

**Environment**:
- Qovery version (use `qovery version`): 0.20.0
- OS and version: Windows 10 Pro 1809
- Others:

![auth-error](https://user-images.githubusercontent.com/214914/79562288-79d93200-80b3-11ea-9c5a-71a8b22a0020.png)

**Comment by evoxmusic** [comment]
Hi @kkapelon , can you try again with the newer version of the CLI ?

**Comment by evoxmusic** [comment]
Please reopen it if it is still the case. Romaric
