### ISSUE TITLE
Be able to deploy an environment as type 'PREVIEW'

### ISSUE THREAD

**Issue by jmeiss** [Qovery/qovery-cli#150]
**What would you like to be added**:
When enabling the auto-creation of preview environment, they have a `type` set as `PREVIEW`.
<img width="285" alt="image" src="https://user-images.githubusercontent.com/227276/227231447-dda6480e-6f5e-4839-a9f5-a7c08dd8e58d.png">

I would have expect to be able to set that type when cloning an environment from the CLI via

```
        qovery environment clone \
          --organization <org> \
          --project WebApp \
          --environment blueprint \
          --environment-type preview \
          --new-environment-name $ENVIRONMENT_NAME
```

But when I do that, they are flagged as `DEV` instead of `PREVIEW`

**Why is this needed**:
To make the difference between each environment types

**Comment by evoxmusic** [comment]
Hi @jmeiss , the environment type `PREVIEW` can't be set via the API. However, we plan to add a tag feature that would eventually replace the type of environment. It would be fully customizable and I think it would help you in that case. At the moment we can't proceed with you request but I'll keep you posted once the tags are available
