### ISSUE TITLE
Be able to deploy several databases at once

### ISSUE THREAD

**Issue by jmeiss** [Qovery/qovery-cli#151]
**What would you like to be added**:
Like we can do to deploy containers or jobs. I would expect to be able to deploy several databases with a single command line:

```
qovery database deploy \
          --organization <org> \
          --project WebApp \
          --environment "[PR-${{ steps.PR.outputs.number }}] ${{ steps.PR.outputs.pr_title }}" \
          --databases "PostgreSQL,redis" \
          --watch
```

**Why is this needed**:

**Comment by acarranoqovery** [comment]
Hi @jmeiss ,

this is already possible via the `--databases` command, like in your example
