### ISSUE TITLE
Quick start does not work on Windows 10

### ISSUE THREAD

**Issue by kkapelon** [Qovery/qovery-cli#16]
**What happened**:
I followed the instructions for the quick start and expected to see my deployment but it never happened

**What you expected to happen**:
To see my deployment using `qovery status`

**How to reproduce it (as minimally and precisely as possible)**:
I just followed the quick start guide on a Windows 10 laptop

**Anything else we need to know?**:
I am attaching a screenshot

**Environment**:
- Qovery version (use `qovery version`): 0.20.0
- OS and version: Windows 10 Pro 1809 
- Others: My repo is here https://github.com/kostis-codefresh/simple-example

![no-deployment](https://user-images.githubusercontent.com/214914/79562994-9b86e900-80b4-11ea-843e-bb1a99c5e25d.png)

**Comment by evoxmusic** [comment]
Hi @kkapelon , can you try again with the [new Qovery starter guide](https://guide.qovery.com)? Thanks

**Comment by evoxmusic** [comment]
Please reopen it if it is still the case. Romaric
