### ISSUE TITLE
Add arguments to context set

### ISSUE THREAD

**Issue by jmeiss** [Qovery/qovery-cli#175]
**What would you like to be added**:

I'd like to be able to pass arguments to `qovery context set`

**Why is this needed**:
To be able to call it from a CI

https://discuss.qovery.com/t/cli-how-can-i-know-if-an-environment-already-exists/1838/2

**Comment by benjaminch** [comment]
Thanks a lot for reporting, we will work on it ASAP.

**Comment by evoxmusic** [comment]
I'm taking a looking at this issue - thank you for reporting @jmeiss
