### ISSUE TITLE
Cannot perform authentication in WSL Windows 10

### ISSUE THREAD

**Issue by pyk** [Qovery/qovery-cli#20]
**What happened**:

```
% qovery auth --debug
DEBU[0000] debug flag is set to true

Opening your browser, waiting for your authentication...
```

Browser not opened and there is no authentication link provided.

**What you expected to happen**:

Browser opened, or at least I can click authroization link manually.

**How to reproduce it (as minimally and precisely as possible)**:

Open ubuntu WSL in Windows 10, then:

```
% curl -s https://get.qovery.com | sudo bash
[sudo] password for pyk:
Downloading Qovery CLI archive...
Uncompressing qovery binary in /usr/local/bin directory

Qovery CLI is installed, you can now use 'qovery' command line
% qovery auth

Opening your browser, waiting for your authentication...
^C
% qovery auth --help
AUTH do auth on Qovery service. For example:

        qovery auth

Usage:
  qovery auth [flags]

Flags:
  -h, --help   help for auth

Global Flags:
      --debug   Enable debugging when true.
% qovery auth --debug
DEBU[0000] debug flag is set to true

Opening your browser, waiting for your authentication...
```

**Anything else we need to know?**:

**Environment**:
- Qovery version (use `qovery version`): 0.24.2
- OS and version: Ubuntu in WSL
- Others:

**Comment by evoxmusic** [comment]
Hi @pyk , thanks for this limitation report. We are working on a auth headless solution. I'll keep you posted

**Comment by evoxmusic** [comment]
Hi @pyk , you can update your CLI and do `qovery auth --headless`. Romaric
