### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Ali1Ammar** [Qovery/qovery-cli#21]
when run qovery init i get

>  2020/05/11 21:03:08 open /.qovery.yml: permission denied

without create .qovery.yml

`

> Reply to the following questions to initialize Qovery for this application
> For more info: https://docs.qovery.com
> ✔ No
> ✔ An existing project
> ✔ *****
> ✔ AWS | Ohio (aws/us-east-2)
> ✔ Yes
> ✔ MySQL
> ✔ latest
> ✓ database: mysql version: 8.0
> ✔ No
> 2020/05/11 21:03:08 open /.qovery.yml: permission denied

`

- Qovery version : 0.26.1
- OS : manjaro

**Comment by evoxmusic** [comment]
Hi @Ali1Ammar , do you own the write rights on your project folder? Can you check please?

**Comment by Ali1Ammar** [comment]
i have 777 permission

**Comment by evoxmusic** [comment]
@deimosfr any idea?
@Ali1Ammar can you copy/paste the full output when you exec `qovery init`?

**Comment by Ali1Ammar** [comment]
> aliammar@aliammar simple-example-node]$ qovery init
> You already have a .qovery.yml file
> ✔ Yes
> 
>  .d88888b.  .d88888b. 888     88888888888888888888b.Y88b   d88P
> d88P" "Y88bd88P" "Y88b888     888888       888   Y88bY88b d88P
> 888     888888     888888     888888       888    888 Y88o88P
> 888     888888     888Y88b   d88P8888888   888   d88P  Y888P
> 888     888888     888 Y88b d88P 888       8888888P"    888
> 888 Y8b 888888     888  Y88o88P  888       888 T88b     888
> Y88b.Y8b88PY88b. .d88P   Y888P   888       888  T88b    888
>  "Y888888"  "Y88888P"     Y8P    8888888888888   T88b   888
>        Y8b
> 
> Reply to the following questions to initialize Qovery for this application
> For more info: https://docs.qovery.com
> ✔ No
> ✔ An existing project
> ✔ getting-started
> ✔ AWS | Oregon (aws/us-west-2)
> ✔ Yes
> ✔ MySQL
> ✔ latest
> ✓ database: mysql version: 8.0
> ✔ No
> 2020/05/11 22:50:26 open /.qovery.yml: permission denied



> [aliammar@aliammar simple-example-node]$ stat ./
>   File: ./
>   Size: 4096            Blocks: 8          IO Block: 4096   directory
> Device: 803h/2051d      Inode: 12587708    Links: 7
> Access: (0777/drwxrwxrwx)  Uid: ( 1000/aliammar)   Gid: ( 1000/aliammar)
> Access: 2020-05-11 22:07:10.518225812 +0300
> Modify: 2020-05-11 22:07:16.884876044 +0300
> Change: 2020-05-11 22:50:04.001412786 +0300
>  Birth: 2020-05-11 22:07:10.518225812 +0300
> [aliammar@aliammar simple-example-node]$ 
>

**Comment by evoxmusic** [comment]
@deimosfr can you check why the CLI tried to write in / ?
```bash
 2020/05/11 22:50:26 open /.qovery.yml: permission denied
```

**Comment by deimosfr** [comment]
Hi,

I'm on Arch and also got the issue. I'm going to fix it, thanks for the report. I let you know once it will be fixed.

Thanks

**Comment by deimosfr** [comment]
I've fixed the issue, I'm building a new release now, should be available in a few minutes.

Thanks again for your report
