### ISSUE TITLE
upgrade complete but didn't change version

### ISSUE THREAD

**Issue by Ali1Ammar** [Qovery/qovery-cli#23]
```
[aliammar@aliammar learnnest]$ qovery upgrade
Upgrading Qovery CLI to version 0.26.4
[aliammar@aliammar learnnest]$ qovery version
0.26.1[aliammar@aliammar learnnest]$ 
```
when upgrade no things change and still in old version
if i try upgrade again same things happens

**Environment**:
- OS and version: manjaro

**Comment by Ali1Ammar** [comment]
i found new version in 
> /tmp/qovery/

and replace it with old  one in 

> /usr/local/bin/

and work fine

**Comment by deimosfr** [comment]
Thanks for the report, I'll take a look

**Comment by deimosfr** [comment]
Hi,

It's a permission issue, can you please upgrade with sudo:
```
sudo qovery upgrade
```
Thanks

**Comment by Ali1Ammar** [comment]
yes it is work with sudo 
thank you
