### ISSUE TITLE
Add a "containers" flag to "qovery container redeploy"

### ISSUE THREAD

**Issue by jmeiss** [Qovery/qovery-cli#247]
**What would you like to be added**:
Add a flag "containers" to the `redeploy` command

**Why is this needed**:
to redeploy multiple containers simultaneously, as we can do with the `deploy` command

**Comment by acarranoqovery** [comment]
Hi @jmeiss ,

you can use the `deploy` command. The `redeploy` is a legacy one that we will decommission since it has the same effect than the `deploy` as long as you don't specify the `--tag`
