### ISSUE TITLE
[Minor] Got "missing EXPOSE 1-65535" despite I have an EXPOSE

### ISSUE THREAD

**Issue by cecton** [Qovery/qovery-cli#32]
**What happened**:

I got this error when running `qovery status` on a newly setup project:

```
ERROR:   missing "EXPOSE 1-65535" instruction in the Dockerfile
SOLUTION: Add EXPOSE {your application port} (port range: 1-65535) instruction inside your Dockerfile
```

Despite having an expose in my Dockerfile:

```Dockerfile
EXPOSE 8080/tcp
```

I got it fixed by removing the `/tcp` but this is valid syntax: https://docs.docker.com/engine/reference/builder/#expose

**What you expected to happen**:

No error.

**How to reproduce it (as minimally and precisely as possible)**:

Provide the protocol to the EXPOSE.

**Anything else we need to know?**:

Minor issue but can be confusing for newcomers.

**Environment**:
- Qovery version (use `qovery version`): 0.31.6
- OS and version: ArchLinux
- Others:

**Comment by evoxmusic** [comment]
Thanks for reporting this issue @cecton . We are going to fix it

**Comment by evoxmusic** [comment]
Hi @cecton , thanks for the report - It's fixed and gonna released today
