### ISSUE TITLE
Launched qovery init on second drive

### ISSUE THREAD

**Issue by MacLikorne** [Qovery/qovery-cli#4]
**What happened**:
Tried to init qovery in a project stored on the second drive

**What you expected to happen**:
Qovery initialized

**How to reproduce it (as minimally and precisely as possible)**:
Init qovery on a non boot drive

**Anything else we need to know?**:
ERROR ==> panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x77a900]

goroutine 1 [running]:
qovery.go/api.CheckHTTPResponse(0x0)
        /home/runner/work/qovery-cli/qovery-cli/api/api.go:18 +0x30
qovery.go/api.GetAccount(0xc1c3c0, 0xc0000da480, 0x0, 0x0)
        /home/runner/work/qovery-cli/qovery-cli/api/account.go:21 +0x23e
qovery.go/cmd.glob..func9(0x130d040, 0x1336e60, 0x0, 0x0)
        /home/runner/work/qovery-cli/qovery-cli/cmd/init.go:39 +0x8e
github.com/spf13/cobra.(*Command).execute(0x130d040, 0x1336e60, 0x0, 0x0, 0x130d040, 0x1336e60)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x130d7c0, 0xc00005ff50, 0xc0001b9f50, 0x405aa6)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x302
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/runner/work/qovery-cli/qovery-cli/qovery.go:10 +0x38

**Environment**:
- Qovery version (use `qovery version`): 0.7.1
- OS and version: win10 1909
- Others: powershell 5

**Comment by deimosfr** [comment]
I tried to reproduce it without success.

After discussion with you, we found that it may comes from the permissions on your computer. You had issues with qovery binary installed on D: while your system is on C:

Installing Qovery on C: works well and is an acceptable workaround from your point of view.

If someone else have similar issue, you're welcome to paste your error here and we'll dig more on that issue. I let this ticket open for the moment
