### ISSUE TITLE
"qovery deploy list" prints commits from other branches than the current branch

### ISSUE THREAD

**Issue by pjeziorowski** [Qovery/qovery-cli#8]
**What happened**:
`qovery deploy list` prints a list of commits - being on master branch, commits from my feature branch are also printed:

![image](https://user-images.githubusercontent.com/44570539/75191444-9eb7c580-5752-11ea-989a-0f516b6bcded.png)

Commits on the screenshot above are printed as commits from 'master', yet they were not pushed/merged to master yet. Those are commits from other branch.

**What you expected to happen**:
`qovery deploy list` print a list of commits only from the current branch

**How to reproduce it (as minimally and precisely as possible)**:
Create a new branch, commit & push some changes, checkout to master and run `qovery deploy list`. 

You could also use my project as an example - https://github.com/appwish/wishservice
Compare `qovery deploy list` output on 'master' and 'qovery' branches.

**Environment**:
- Qovery version (use `qovery version`): 0.12.2
- OS and version: macOS 10.15.3

**Comment by deimosfr** [comment]
It has been fixed in dev branch

**Comment by deimosfr** [comment]
It has been fixed in dev branch
